yaml
name: Node Social Backend CI
on:
  push:
    branches:
      - development
      - main

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Using NodeJS
        uses: actions/setup-node@v1
        with: 
          node-version: '18.x'

      - name: Run NPM
        run: npm i

      - name: Run CI Tests
        run: npm run test
