@baseUrl = http://localhost:5000
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/post/comment/64f7158ea404b18de34a8bca
Content-Type: application/json
Accept: application/json
withCredentials: true


###
GET {{baseUrl}}/{{urlPath}}/post/reaction/64c8fba1b9995d4a22d59f23/squaredr
Content-Type: application/json
Accept: application/json
withCredentials: true


###
GET {{baseUrl}}/{{urlPath}}/post/reaction-by-username/squaredr
Content-Type: application/json
Accept: application/json
withCredentials: true


###
POST {{baseUrl}}/{{urlPath}}/post/comment
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "64f82fdf8e4ef44e904b8d30",
  "postId": "64f82ffd8e4ef44e904b8d35",
  "comment": "Adding one more test comment",
  "profilePicture": "https://res.cloudinary.com/duywfhwqq/image/upload/v1689069231/64ad26aa5141b6769c074770"
}


###
GET {{baseUrl}}/{{urlPath}}/post/comment/64c8fba1b9995d4a22d59f23
Content-Type: application/json
Accept: application/json
withCredentials: true

# {
#   "userTo": "64c3bfb40fe3b1cbca2aec55",
#   "postId": "64c8fba1b9995d4a22d59f23",
#   "comment": "Adding one more test comment",
#   "profilePicture": "https://res.cloudinary.com/duywfhwqq/image/upload/v1689069231/64ad26aa5141b6769c074770"
# }


###
GET {{baseUrl}}/{{urlPath}}/post/comment-names/64c8fba1b9995d4a22d59f23
Content-Type: application/json
Accept: application/json
withCredentials: true

# {
#   "userTo": "64c3bfb40fe3b1cbca2aec55",
#   "postId": "64c8fba1b9995d4a22d59f23",
#   "comment": "Adding one more test comment",
#   "profilePicture": "https://res.cloudinary.com/duywfhwqq/image/upload/v1689069231/64ad26aa5141b6769c074770"
# }


###
GET {{baseUrl}}/{{urlPath}}/post/single-comment/64c8fba1b9995d4a22d59f23/64ccf4f97f939395099e13a7
Content-Type: application/json
Accept: application/json
withCredentials: true

# {
#   "userTo": "64c3bfb40fe3b1cbca2aec55",
#   "postId": "64c8fba1b9995d4a22d59f23",
#   "comment": "Adding one more test comment",
#   "profilePicture": "https://res.cloudinary.com/duywfhwqq/image/upload/v1689069231/64ad26aa5141b6769c074770"
# }
