name: Node Social Backend CI
on:
  push:
    branches:
      - development

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Using NodeJS
        uses: actions/setup-node@v1
        with: 
          node-version: '18.x'

      - name: Run NPM
        run: npm i

      - name: Run CI Tests
        env:
          JWT_TOKEN: ${{secrets.JWT_TOKEN}}
          SECRET_KEY_ONE: ${{secrets.SECRET_KEY_ONE}}
          SECRET_KEY_TWO: ${{secrets.SECRET_KEY_TWO}}
        run: npm run test
