name: Node Social Backend CI
on:
  push:
    branches: [ development, main ]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Using NodeJS
        uses: actions/setup-node@v1
        with: 
          node-version: '18.x'

      - name: Run NPM
        run: npm i

      - name: Run CI Tests
        env: 
          JWT_TOKEN: 'random-key-for-testing-ci'
          SECRET_KEY_ONE: 'random-key-for-testing-ci'
          SECRET_KEY_TWO: 'random-key-for-testing-ci'
        run: npm run test
